[package]
name = "day3-2"
version = "0.1.0"
authors = ["Joshua Scheel <jscheel42@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc_util = { path = "../aoc_util" }